[rule_configuration]
webview_pre_execute = ''
common_track_args = [
    '^utm_[a-zA-Z0-9_]+$',
    '^spm(_[a-zA-Z0-9_]+)?$'
]

[[rules]]
regex = '(https?:\/\/)?t\.cn\/[a-zA-Z0-9\?\-\.\+\/_%&=~]+'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?dwz\.cn\/[a-zA-Z0-9\?\-\.\+\/_%&=~]+'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?t\.co\/[a-zA-Z0-9\?\-\.\+\/_%&=~]+'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?bit\.ly\/[a-zA-Z0-9\?\-\.\+\/_%&=~]+'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?goo\.gl\/[a-zA-Z0-9\?\-\.\+\/_%&=~]+'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?g\.co\/[a-zA-Z0-9\?\-\.\+\/_%&=~]+'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?aka\.ms\/[a-zA-Z0-9\?\-\.\+\/_%&=~]+'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?go\.microsoft\.com\/fwlink\/\?linkid=\d+(&[a-zA-Z0-9\-\.\+\/_%&=~]+)?'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?trib.al\/[a-zA-Z0-9\?\-\.\+\/_%&=~]+'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?b23.tv\/[a-zA-Z0-9\?\-\.\+\/_%&=~]+'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?[a-z].tb.cn\/[a-zA-Z0-9_\.\-]+(\?[a-zA-Z0-9_\.\-]+=[a-zA-Z0-9_\.\-]+)?'
action = 'SHORT_LINK'

[[rules]]
regex = '(https?:\/\/)?item(\.m)?\.taobao\.com\/item\.htm\?[a-zA-Z0-9\-\.\+\/_%&=~]+'
action = 'PARAM_WHITELIST'
params = [
    'id'
]

[[rules]]
regex = '(https?:\/\/)?h5\.m\.taobao\.com\/awp\/core\/detail\.htm\?[a-zA-Z0-9\-\.\+\/_%&=~]+'
action = 'PARAM_WHITELIST'
params = [
    'id'
]

[[rules]]
regex = '(https?:\/\/)?.+\.taobao\.com\/'
action = 'PARAM_WHITELIST'
params = [
    'id'
]

[[rules]]
regex = '(https?:\/\/)?a\.m\.taobao\.com\/i\d+\.htm\?[a-zA-Z0-9\-\.\+\/_%&=~]+'
action = 'WEB_VIEW'
javascript = '''
document.onUrlPreLoad = (url) => {
    control.completion(
        'https://item.taobao.com/item.htm?id=' +
        originalUrl.substring(originalUrl.indexOf('i') + 1, originalUrl.indexOf('.htm'))
    );
}
'''
[[rules]]
regex = 'https:\/\/(x|twitter)\.com\/[a-zA-Z0-9\-_.]+\/status\/\d+\/?\?([a-zA-Z]+=[0-9a-zA-Z\-_]+&?)+'
action = 'PARAM_WHITELIST'
params = [
    'p'
]

[[rules]]
regex = '(https?:\/\/)?(www\.)bilibili\.com\/video\/[a-zA-Z0-9]+(\?[a-zA-Z0-9\-\.\+\/_%&=~]+)?'
action = 'PARAM_WHITELIST'
params = [
    'p'
]

[[rules]]
regex = '(https?:\/\/)?mp\.weixin\.qq\.com\/s\?[a-zA-Z0-9\-\.\+\/_%&=~]+'
action = 'PARAM_WHITELIST'
params = [
    '__biz',
    'mid',
    'idx',
    'sn'
]

[[rules]]
regex = '(https?:\/\/)?[0-9a-zA-Z]+(\.m)?\.youzan\.com\/wscshop\/showcase\/feature\?[a-zA-Z0-9\-\.\+\/_%&=~]+'
action = 'PARAM_WHITELIST'
params = [
    'alias'
]

[[rules]]
regex = '(https?:\/\/)?(m\.)?music.163.com\/[0-9a-zA-Z\/]+\?[a-zA-Z0-9\-\.\+\/_%&=~]+'
action = 'PARAM_WHITELIST'
params = [
    'id'
]